model:
  # this will be mounted from host system to docker container via
  # runner script. stretch goal: hf support
  name_or_path: /artifacts-local

generate:
  max_tokens: 4096
  max_context_length: 4096
  temperature: 0.1
  top_k: 50
  top_p: 1.0
  drop_long_outputs: true

pipeline:
  input_file_dir: /asdf-input
  output_file_dir: /asdf-output
  num_workers: 1
  generation_batch_size: 256

