model:
  # this will be mounted from host system to docker container via
  # runner script. stretch goal: hf support
  name_or_path: /artifacts-local
  tensor_parallel_size: 1
  num_scheduler_steps: 1  # 8 is faster but not supported by all models

generate:
  max_tokens: 4096
  max_context_length: 4096
  temperature: 0.1
  top_k: 50
  top_p: 1.0

pipeline:
  input_file_dir: /asdf-input
  output_file_dir: /asdf-output
  num_gpus: 1
  generation_batch_size: 256

